### ISSUE TITLE
This is not working with nuget installation

### ISSUE THREAD

**Issue by Smx27** [chrilleson/Templates.WebApi#40]
I tried this package downloaded from nuget 
Here is the error 
![image](https://github.com/user-attachments/assets/8d037ef5-0df8-4ef2-9ad3-286967c20565)

to fix this rather than using src you have to use template and 
you have to add a template csproj 
checkout this doc 
https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-template-package?pivots=dotnet-8-0

then you can pack and publish this to nuget hope this help you out build a great template

**Comment by chrilleson** [comment]
Thanks. Will look into it

**Comment by chrilleson** [comment]
Thank you @Smx27 for creating this issue and pointing this out. It is now fixed and released to NuGet. please let me know what you think of this project and if you have any ideas/improvements 😊
